[library.fpga-switch]
location = /home/justint/Documents/fpga-switch
sync-uri = .
sync-type = local
auto-sync = true

[library.svlib.git]
location = fusesoc_libraries/svlib.git
sync-uri = git@github.com:justinT21/svlib.git
sync-type = git
auto-sync = true

